data:
  data_mean: [0.485, 0.456, 0.406] # rgb
  data_std: [0.229, 0.224, 0.225] # rgb
  data_root: './dataset'
  image_size: [192,192]

model:
  # backbone: "mobilenet"
  backbone: "shufflenetv2"
  num_class: 2


train:
  epoch: 100
  batch_size: 2
  test_epoch: 1
  num_workers: 8
  lr_scheduler: "cosinelr" # ["steplr", "cosinelr"]

  optimizer: "adamw" # ["adam",  "adamw", "sgd"]
  lr: 0.001
  weight_decay: 0.001
  save_weight_dir: "assets"
  gpu_id: 0
  
  pretrain: 'weights/shufflenetv2_x0.5-f707e7126e.pth'
  log_dir: 'experiments'

eval:
  threshold: 0.5

onnx:
  save_path: "assets"
